name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Build and push Docker image
      uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
      with:
        context: .
        platforms: ${{ matrix.platforms }}
        push: true
        outputs: type=image,name=target,annotation-index.org.opencontainers.image.description=My multi-arch image
